### PR TITLE
add sourcemaps support

### PR DESCRIPTION
**Pull request by qraynaud**
This is very raw but it should work as intended!

### CODE REVIEW

**Comment by alexlawrence** [comment]
This commit introduces new node modules, however I can´t see any changes to the package.json

**Comment by qraynaud** [comment]
Strange, I do see them myself…

**Comment by alexlawrence** [comment]
Haha, Sorry :octocat:

**Comment by qraynaud** [comment]
Please keep in stand-by. I might have found a small issue after extended testing. Coming back about this…

**Comment by qraynaud** [comment]
Ok it works properly. My problem is caused by applySourceMap after a lot of changes. That is not relevant here. It is the algorithm in mozilla's `sourcemaps` module that is too naïve.

**Comment by qraynaud** [comment]
Is this looking good to you ?

**Comment by natew** [comment]
@qraynaud @alexlawrence is this working? I need to wrap a huge file with just a few lines, and no way to keep source maps at the moment.

**Comment by qraynaud** [comment]
@natew : you can try gulp-wrap-commonjs-sourcemaps which is a fork of this module with my patch applied to see if it works for you.

**Comment by mwager** [comment]
Sorry for the late response. Looks good!

**Pull request merged**
